import AOSInit from "@/lib/aos";
import "./globals.css";
import { Analytics } from "@vercel/analytics/react";
import Navbar from "@/components/Navbar";
import Title from "@/components/Title";
import Layout from "@/components/Layout";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <AOSInit />
      <link rel="icon" href="/favicon.ico" sizes="any" />
      <Title />
      <body>
        <Layout>{children}</Layout>
        <Analytics />
      </body>
    </html>
  );
}
