import AOSInit from "@/lib/aos";
import "./globals.css";
import { Analytics } from "@vercel/analytics/react";
import Navbar from "@/components/Navbar";
import Title from "@/components/Title";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <AOSInit />
      <link rel="icon" href="/favicon.ico" sizes="any" />
      <Title />
      <body className="md:flex">
        <Navbar />
        <div className="w-full overflow-x-hidden md:h-screen py-20 md:py-3 bg-white text-black  md:overflow-y-scroll p-5">
          {children}
        </div>
        <Analytics />
      </body>
    </html>
  );
}
