import AOSInit from "@/lib/aos";
import "./globals.css";
import { Analytics } from "@vercel/analytics/react";
import Title from "@/components/Title";
import Layout from "@/components/Layout";
import { Session } from "next-auth";
import Provider from "@/components/Provider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <AOSInit />
      <link rel="icon" href="/favicon.ico" sizes="any" />
      <Title />
      <body>
        <Provider>
          <Layout>{children}</Layout>
          <Analytics />
        </Provider>
      </body>
    </html>
  );
}
